version: '3.1'

services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user_mongo
      MONGO_INITDB_ROOT_PASSWORD: pass_mongo

  app-backend:
    image: app-backend:1.0.0
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - mongo